# Generated by Django 4.1.5 on 2023-01-17 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyDataTable',
            fields=[
                ('comid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('companyname', models.CharField(max_length=100)),
                ('comregno', models.CharField(max_length=500)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=50)),
                ('preffield', models.CharField(max_length=300)),
                ('linkedin', models.CharField(blank=True, max_length=1000, null=True)),
                ('createtimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatetimestamp', models.DateTimeField(auto_now_add=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flyerdata',
            fields=[
                ('flyerid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comid', models.TextField()),
                ('jobfield', models.CharField(max_length=100)),
                ('jobpost', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=1000)),
                ('flyerimage', models.ImageField(upload_to='')),
                ('createtimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatetimestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentDataTable',
            fields=[
                ('stuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=200)),
                ('degree', models.TextField(blank=True, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=1000, null=True)),
                ('createtimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatetimestamp', models.DateTimeField(auto_now_add=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='studentflyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyerid', models.TextField()),
                ('comid', models.TextField()),
                ('favorite', models.CharField(max_length=5)),
                ('apply', models.CharField(max_length=5)),
            ],
        ),
    ]
