# Generated by Django 4.1.5 on 2023-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0007_rename_comid_flyerdata_comname'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyerdata',
            name='comid',
            field=models.TextField(default='testCompanyID'),
        ),
        migrations.AlterField(
            model_name='flyerdata',
            name='comname',
            field=models.TextField(default='testcompanyname'),
        ),
    ]
