# Generated by Django 4.1.5 on 2023-01-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0008_flyerdata_comid_alter_flyerdata_comname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentflyer',
            old_name='comid',
            new_name='stuid',
        ),
        migrations.AlterField(
            model_name='studentflyer',
            name='apply',
            field=models.CharField(default='Apply', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentflyer',
            name='favorite',
            field=models.CharField(default='Add to Favorite', max_length=20),
        ),
    ]
