# Generated by Django 4.1.5 on 2023-01-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0010_remove_flyerdata_comid_remove_flyerdata_comname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyerdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkplaceApp.companydatatable'),
        ),
    ]
