# Generated by Django 4.1.5 on 2023-01-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0012_studentapply_studentfavorite_delete_studentflyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=2000)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkplaceApp.studentdatatable')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=5000)),
                ('sender', models.CharField(max_length=200)),
                ('Receiver', models.CharField(max_length=200)),
                ('createtimestamp', models.CharField(max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkplaceApp.companydatatable')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkplaceApp.studentdatatable')),
            ],
        ),
        migrations.CreateModel(
            name='ComNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=2000)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkplaceApp.companydatatable')),
            ],
        ),
    ]
