# Generated by Django 4.1.5 on 2023-01-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0015_comnotification_createtimestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comnotification',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
