# Generated by Django 4.1.5 on 2023-01-30 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0016_alter_comnotification_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comnotification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stunotification',
            name='id',
        ),
        migrations.AddField(
            model_name='comnotification',
            name='ComNotificationId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='msgid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='stunotification',
            name='StuNotificationId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
