# Generated by Django 4.1.5 on 2023-01-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0018_comnotification_markasread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comnotification',
            name='createtimestamp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flyerdata',
            name='createtimestamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flyerdata',
            name='updatetimestamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='createtimestamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stunotification',
            name='createtimestamp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
