# Generated by Django 4.1.5 on 2023-01-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0019_alter_comnotification_createtimestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ReceiverID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='senderID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
