# Generated by Django 4.1.5 on 2023-02-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceApp', '0020_message_receiverid_message_senderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='MarkAsRead',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
